apiVersion: v1
kind: Service
metadata:
  namespace: sidecar-namespace
  name: sidecar-app
spec:
  type: NodePort
  ports:
    - name: main-app
      port: 8088
      targetPort: main-app-port
      nodePort: 30005
    - name: sidecar-app
      port: 8090
      targetPort: sidecar-port
      nodePort: 30010
  selector:
    app: sidecar-app
