apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sidecar-namespace
  name: sidecar-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-app
  template:
    metadata:
      labels:
        app: sidecar-app
    spec:
      containers:
        - name: main-app
          image: main-app
          imagePullPolicy: "Never"
          ports:
            - name: main-app-port
              containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: SERVER_PORT
              value: "8080"
        - name: custom-nginx
          image: custom-nginx
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: nginx-port
              containerPort: 9090
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
        - name: authorisation-server
          image: authorisation-server
          imagePullPolicy: "IfNotPresent"
          ports:
            - name: auth-port
              containerPort: 8081
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: SERVER_PORT
              value: "8081"