apiVersion: v1
kind: Service
metadata:
  namespace: sidecar-namespace
  name: sidecar-app
spec:
  type: NodePort
  ports:
    - name: sidecar-app
      port: 8090
      targetPort: sidecar-port
      nodePort: 30010
  selector:
    app: sidecar-app
