apiVersion: v1
kind: Service
metadata:
  namespace: sidecar-namespace
  name: sidecar-app
spec:
  type: NodePort
  ports:
    - name: nginx-app
      port: 9090
      targetPort: nginx-port
      nodePort: 30010
  selector:
    app: sidecar-app
